[tool.poetry]
name = "python_tsp"
version = "0.1.0"
description = ""
authors = ["Fillipe Goulart <fillipe.gsm@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.18.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
sphinx = "^3.1.1"
ipdb = "^0.13.2"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
